package com.hnieu.crtvn.entity;
// Generated 2019-2-23 22:25:06 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * College generated by hbm2java
 */
@Entity
@Table(name = "college", catalog = "crtvn")
public class College implements java.io.Serializable {

	private Integer id;
	private String name;
	private String secretary;
	private String dean;
	private Integer reserve1;
	private String reserve2;
	private Set<Profession> professions = new HashSet<Profession>(0);
	private Set<Classroom> classrooms = new HashSet<Classroom>(0);
	private Set<Academician> academicians = new HashSet<Academician>(0);
	private Set<Etime> etimes = new HashSet<Etime>(0);

	public College() {
	}

	public College(String name, String secretary, String dean) {
		this.name = name;
		this.secretary = secretary;
		this.dean = dean;
	}

	public College(String name, String secretary, String dean, Integer reserve1, String reserve2,
			Set<Profession> professions, Set<Classroom> classrooms, Set<Academician> academicians, Set<Etime> etimes) {
		this.name = name;
		this.secretary = secretary;
		this.dean = dean;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
		this.professions = professions;
		this.classrooms = classrooms;
		this.academicians = academicians;
		this.etimes = etimes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "secretary", nullable = false, length = 10)
	public String getSecretary() {
		return this.secretary;
	}

	public void setSecretary(String secretary) {
		this.secretary = secretary;
	}

	@Column(name = "dean", nullable = false, length = 10)
	public String getDean() {
		return this.dean;
	}

	public void setDean(String dean) {
		this.dean = dean;
	}

	@Column(name = "reserve1")
	public Integer getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(Integer reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2", length = 50)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "college")
	public Set<Profession> getProfessions() {
		return this.professions;
	}

	public void setProfessions(Set<Profession> professions) {
		this.professions = professions;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "college")
	public Set<Classroom> getClassrooms() {
		return this.classrooms;
	}

	public void setClassrooms(Set<Classroom> classrooms) {
		this.classrooms = classrooms;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "college")
	public Set<Academician> getAcademicians() {
		return this.academicians;
	}

	public void setAcademicians(Set<Academician> academicians) {
		this.academicians = academicians;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "college")
	public Set<Etime> getEtimes() {
		return this.etimes;
	}

	public void setEtimes(Set<Etime> etimes) {
		this.etimes = etimes;
	}

}
