package com.hnieu.crtvn.entity;
// Generated 2019-2-24 23:23:31 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Exam generated by hbm2java
 */
@Entity
@Table(name = "exam", catalog = "crtvn")
public class Exam implements java.io.Serializable {

	private Integer id;
	private Classs classs;
	private Examination examination;
	private Student student;
	private int seatNo;
	private Integer reserve1;
	private String reserve2;

	public Exam() {
	}

	public Exam(Classs classs, Examination examination, Student student, int seatNo) {
		this.classs = classs;
		this.examination = examination;
		this.student = student;
		this.seatNo = seatNo;
	}

	public Exam(Classs classs, Examination examination, Student student, int seatNo, Integer reserve1,
			String reserve2) {
		this.classs = classs;
		this.examination = examination;
		this.student = student;
		this.seatNo = seatNo;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CCID", nullable = false)
	public Classs getClasss() {
		return this.classs;
	}

	public void setClasss(Classs classs) {
		this.classs = classs;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EID", nullable = false)
	public Examination getExamination() {
		return this.examination;
	}

	public void setExamination(Examination examination) {
		this.examination = examination;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SID", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "seatNo", nullable = false)
	public int getSeatNo() {
		return this.seatNo;
	}

	public void setSeatNo(int seatNo) {
		this.seatNo = seatNo;
	}

	@Column(name = "reserve1")
	public Integer getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(Integer reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2")
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

}
