package com.hnieu.crtvn.entity;
// Generated 2019-2-23 22:25:06 by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonBackReference;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Profession generated by hbm2java
 */
@Entity
@Table(name = "profession", catalog = "crtvn", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Profession implements java.io.Serializable {

	private Integer id;
	private College college;
	private String code;
	private String name;
	private String departmentHead;
	private String secretary;
	private Integer reserve1;
	private String reserve2;
	private Set<Teacher> teachers = new HashSet<Teacher>(0);
	private Set<Course> courses = new HashSet<Course>(0);
	private Set<Examination> examinations = new HashSet<Examination>(0);
	private Set<Classs> classses = new HashSet<Classs>(0);

	public Profession() {
	}

	public Profession(College college, String code, String name, String departmentHead, String secretary) {
		this.college = college;
		this.code = code;
		this.name = name;
		this.departmentHead = departmentHead;
		this.secretary = secretary;
	}

	public Profession(College college, String code, String name, String departmentHead, String secretary,
                      Integer reserve1, String reserve2, Set<Teacher> teachers, Set<Course> courses,
                      Set<Examination> examinations, Set<Classs> classses) {
		this.college = college;
		this.code = code;
		this.name = name;
		this.departmentHead = departmentHead;
		this.secretary = secretary;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
		this.teachers = teachers;
		this.courses = courses;
		this.examinations = examinations;
		this.classses = classses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CID", nullable = false)
	public College getCollege() {
		return this.college;
	}

	public void setCollege(College college) {
		this.college = college;
	}

	@Column(name = "code", unique = true, nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "departmentHead", nullable = false, length = 10)
	public String getDepartmentHead() {
		return this.departmentHead;
	}

	public void setDepartmentHead(String departmentHead) {
		this.departmentHead = departmentHead;
	}

	@Column(name = "secretary", nullable = false, length = 10)
	public String getSecretary() {
		return this.secretary;
	}

	public void setSecretary(String secretary) {
		this.secretary = secretary;
	}

	@Column(name = "reserve1")
	public Integer getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(Integer reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2")
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profession")
	public Set<Teacher> getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profession")
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profession")
	public Set<Examination> getExaminations() {
		return this.examinations;
	}

	public void setExaminations(Set<Examination> examinations) {
		this.examinations = examinations;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profession")
	public Set<Classs> getClassses() {
		return this.classses;
	}

	public void setClassses(Set<Classs> classses) {
		this.classses = classses;
	}

}
