package com.hnieu.crtvn.entity;
// Generated 2019-2-23 22:25:06 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "crtvn", uniqueConstraints = { @UniqueConstraint(columnNames = "IDCard"),
		@UniqueConstraint(columnNames = "SID") })
public class Student implements java.io.Serializable {

	private Integer id;
	private Classs classs;
	private String sid;
	private String name;
	private int gender;
	private String idcard;
	private String phone;
	private int age;
	private String grade;
	private Integer reserve1;
	private String reserve2;
	private Set<Studentselection> studentselections = new HashSet<Studentselection>(0);
	private Set<Exam> exams = new HashSet<Exam>(0);

	public Student() {
	}

	public Student(Classs classs, String sid, String name, int gender, String idcard, int age, String grade) {
		this.classs = classs;
		this.sid = sid;
		this.name = name;
		this.gender = gender;
		this.idcard = idcard;
		this.age = age;
		this.grade = grade;
	}

	public Student(Classs classs, String sid, String name, int gender, String idcard, String phone, int age,
			String grade, Integer reserve1, String reserve2, Set<Studentselection> studentselections, Set<Exam> exams) {
		this.classs = classs;
		this.sid = sid;
		this.name = name;
		this.gender = gender;
		this.idcard = idcard;
		this.phone = phone;
		this.age = age;
		this.grade = grade;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
		this.studentselections = studentselections;
		this.exams = exams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CID", nullable = false)
	public Classs getClasss() {
		return this.classs;
	}

	public void setClasss(Classs classs) {
		this.classs = classs;
	}

	@Column(name = "SID", unique = true, nullable = false, length = 20)
	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	@Column(name = "name", nullable = false, length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "gender", nullable = false)
	public int getGender() {
		return this.gender;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	@Column(name = "IDCard", unique = true, nullable = false, length = 20)
	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "grade", nullable = false, length = 10)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "reserve1")
	public Integer getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(Integer reserve1) {
		this.reserve1 = reserve1;
	}

	@Column(name = "reserve2", length = 50)
	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<Studentselection> getStudentselections() {
		return this.studentselections;
	}

	public void setStudentselections(Set<Studentselection> studentselections) {
		this.studentselections = studentselections;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<Exam> getExams() {
		return this.exams;
	}

	public void setExams(Set<Exam> exams) {
		this.exams = exams;
	}

}
